[tools]
npm = "latest"
node = "24"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[shell_alias]
"exa-search:local" = "node {{config_root}}/src/cli.ts"
"exa:local" = "node {{config_root}}/src/cli.ts"
"search:local" = "node {{config_root}}/src/cli.ts"
